config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'devise/passwords'
  }
  
  devise_scope :user do
    get "users/sign_out", to: "devise/sessions#destroy" 
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "users#top"
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"
  end
  
  get "/users/:user_id/relationships/create", to: "relationships#create"
  get "/users/:user_id/relationships/destroy", to: "relationships#destroy"

  get "/users/:user_id/followings", to: "relationsships#followings"
  get "/users/:user_id/followers", to: "relationsships#followers"


  get "/users/:id", to: "users#show"


  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:new, :create]
  end
  
  get "/posts/:id/destroy", to: "posts#destroy"

  get "posts/:id/favorites/create", to: "favorites#create"
  get "posts/:id/favorites/destroy", to: "favorites#destroy"

  get "posts/:post_id/post_comments/new", to: "post_comments#new"
  get "post_comments/:post_comment_id/destroy", to: "post_comments#destroy"




  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
    end
  end
  
  get "/db_status", to: "health#db_status"

end

app/models/post.rb
class Post < ApplicationRecord
    validates :user_id, presence: true  #誰が投稿したかという情報は必要不可欠なので、user_idにバリデーションを設定する。
    belongs_to :user
    has_one_attached :image #追加
    has_many :favorites, dependent: :destroy
    
    def favorited_by?(user)
        favorites.exists?(user_id: user.id)
    end

    # PostモデルとPostCommentモデルを関連付け
    has_many :post_comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all.order(updated_at: :desc)
        @post_comment = PostComment.new
        if params[:id].present?
            @post = Post.find(params[:id])
            @user = User.find_by(id: @post.user_id)
        else
            @post = Post.new #空のインスタンスを生成
        end
    end

    def new
        if user_signed_in?
            @post = Post.new #空のインスタンスを生成
        else
            flash[:alert] = '新規投稿するにはアカウントを作成してください。またはログインしてください。'
            puts "ログインしていないユーザーが投稿しようとしています。" # デバッグ用
            redirect_to new_user_registration_path # アカウント作成ページへリダイレクト
        end
    end
    
    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        # binding.pry
        if @post.save
            flash[:notice] = '正常に投稿されました。'
            redirect_to action: 'index' 
        else
            flash[:notice] = '投稿に失敗しました。'
            redirect_to action: 'new' 
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            flash[:notice] = '投稿が更新されました。'
            redirect_to action: 'index' 
        else
            flash.now[:alert] = '投稿の更新に失敗しました。'
            redirect_to action: 'edit' 
        end
    end


    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        flash[:notice] = '投稿が削除されました。'
        redirect_to action: 'index' 
    end

    def show
        @post = Post.find(params[:id])
    end

    private
    def post_params #ストロングパラメータ
        params.require(:post).permit(:title, :content, :phoneNumber, :image)  #パラメーターのキー
    end
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<%= form_with model: [@post, @post_comment] do |form| %>
    <%= form.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= form.submit "送信する" %>
<% end %>

<%= link_to "戻る", posts_path%>

app/views/posts/_edit.html.erb
<%= stylesheet_link_tag 'postsIndex', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="postsEdit-all">
    <div>
        <%= form.label :タイトル %><br>
        <%= form.text_field :title, :placeholder =>"#{@post.title}" %>
    </div>
    <div>
        <%= form.label :内容 %><br>
        <%= form.text_area :content, :placeholder =>"#{@post.content}" %> 
    </div>
    <div>
        <%= form.label :電話番号 %><br>
        <%= form.text_area :phoneNumber, :placeholder =>"#{@post.phoneNumber}" %> 
    </div>
    <div>
        <%= form.label :画像 %><br>
        <%= form.file_field :image, :placeholder =>"#{@post.image}" %> 
    </div>
    <div>
        <%= form.submit "更新" %>
    </div>
</div>


app/views/posts/_new.html.erb
<%= stylesheet_link_tag 'postsNew', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="postsNew-all">
    <div>
        <%= form.label :タイトル %><br>
        <%= form.text_field :title %>
    </div>
    <div>
    
        <%= form.label :内容 %><br>
        <%= form.text_area :content %> 
    </div>
    <div>
        <%= form.label :電話番号 %><br>
        <%= form.text_area :phoneNumber %>
    </div>
    <div>
        <%= form.label :画像 %><br>
        <%= form.file_field :image, accept: "image/*" %>
    </div>
    <div>
        <%= form.submit "送信" %>
    </div>
</div>

app/views/posts/edit.html.erb
<%= stylesheet_link_tag 'postsIndex', media: 'all', 'data-turbolinks-track': 'reload' %>
<div>
    <h1>投稿編集ページ</h1>
    <div>
        <%= form_with model: @post, local: true do |form| %>
            <div>
                <%= form.label :タイトル %><br>
                <%= form.text_field :title, :placeholder =>"#{@post.title}" %>
            </div>
            <div>
                <%= form.label :内容 %><br>
                <%= form.text_area :content, :placeholder =>"#{@post.content}" %> 
            </div>
            <div>
                <%= form.submit "更新" %>
            </div>

        <% end %>
    </div>
</div>

<%= link_to "戻る", posts_path%>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'postsIndex', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="postsIndex-all">
    <% if user_signed_in?  %>
        <div class="postsForm-all">
            <h1>新規・更新投稿フォーム</h1>
            <%= form_with model: @post, local: true, html: { multipart: true } do |form| %>
                <% if @post.new_record? %> <!-- 既にデータベースに保存されているか？ -->
                    <%= render :partial => 'new', :locals => {:form => form} %>
                <% else %>
                    <%= render :partial => 'edit', :locals => {:form => form} %>
                <% end %>
            <% end %>
        </div>
    <% end %>

    <h1>投稿一覧</h1>
    <% @posts.each do |post| %>
        <div class="postsContainer">
            <% if post.user.avatar.present?  %>
                <p class="iconImg"><%= image_tag post.user.avatar %></p>
            <% else %>
                <%= image_tag '/assets/defaultUserIcon.png',:alt => 'デフォルトユーザーアイコン' %>
            <% end %>
            <p>投稿者ID：<%= link_to( post.user_id, user_path(id: post.user_id)) %></p>
            <p>投稿ID：<%= link_to( post.id, post_path(id: post.id))%></p>
            <p>タイトル</p>
            <span><%= post.title %></span>

            <p>内容</p>
            <span><%= post.content %></span>

            <p>電話番号</p>
            <span><%= post.phoneNumber %></span></br>

            <% if post.image.attached? %>
                <%= image_tag post.image, size: "150x150" %></br>
            <% else %>
                <%= image_tag '/images/default.jpg', size: "150x150" %></br>
            <% end %>

            <% if user_signed_in? %>
                <div class="postsIndex-link">
                    <div class="edit_post_link">
                        <%= link_to "編集", posts_path(id: post.id) %>
                    </div>
                    <div class="destroy_post_link">
                        <%= link_to "削除", "/posts/#{post.id}/destroy", method: :delete %></br>
                    </div>
                </div>
            <% end %>

            <% if user_signed_in? %>
                <% if post.favorited_by?(current_user) %>
                    <%= link_to "♥", "/posts/#{post.id}/favorites/destroy" %>
                <% else %>
                    <%= link_to "♡", "/posts/#{post.id}/favorites/create" %>
                <% end %>
            <% end %>

            <%= post.favorites.count %> いいね

            <% if user_signed_in? %>
                <% if current_user != post.user %>
                    <% if current_user.following?(post.user) %>
                        <%= link_to "フォロー外す", "/users/#{post.user.id}/relationships/destroy" %>
                    <% else %>
                        <%= link_to "フォローする", "/users/#{post.user.id}/relationships/create" %>
                    <% end %>
                <% end %>
            <% end %>

            <p>フォロー数</p>
            <%= link_to( post.user.followings.count,  user_followings_path(user_id: post.user.id))%>
            <p>フォロワー数</p>
            <%= link_to( post.user.followers.count,  user_followers_path(user_id: post.user.id)) %>

            <p>コメント</p>
            # <%= link_to "コメントする", "/posts/#{post.id}/post_comments/new" %>

            <%= render template: 'post_comments/new', locals: { post: post, post_comment: @post_comment } %>

            <p>コメント件数：<%= post.post_comments.count %></p>

            <% post.post_comments.each do |post_comment| %>
                <%= post_comment.comment %>
                <% if post_comment.user == current_user %>
                    <%= link_to "削除", "post_comments/#{post_comment.id}/destroy" %>
                <% end %>
                </br>
            <% end %>
        </div>
    <% end %>
</div>



app/views/posts/show.html.erb
<%= stylesheet_link_tag 'postsShow', media: 'all', 'data-turbolinks-track': 'reload' %>

<h1>〇〇の投稿の詳細ページ</h1>

<h3>投稿ID</h3>
<%= @post.id %></br>

<%= link_to "戻る", posts_path%>